### ISSUE TITLE
Instructions on how to get the tar file "rn-indy-sdk": "file:rn-indy-sdk-v0.1.7.tgz",

### ISSUE THREAD

**Issue by ILoomans** [animo/aries-mobile-agent-react-native#4]
Hello, 

I was wondering whether there were instructions on how to create the rn-indy-sdk-v0.1.7.tgz file, I see that in the repository there is the tar file aries-framework-javascript but not for rn-indy-sdk. I tried to go to rn-indy-sdk and run npm pack, but that didn't work for me. Hope someone can help!

Ignace

**Comment by karimStekelenburg** [comment]
Hi there!

Thanks for noting, looks like I've left `rn-indy-sdk` as a file dependency by mistake.
You can resolve this by removing the file dependency and adding the version from NPM by running:
```
yarn remove rn-indy-sdk
yarn add rn-indy-sdk
```
Also: in order to get it to work on iOS you'll need to follow step 2 of [this answer](https://github.com/animo/aries-mobile-agent-react-native/issues/1#issuecomment-768546337) **after** running `pod install`.

Hope this helps!

**Comment by TimoGlastra** [comment]
Fixed by #5
